### ISSUE TITLE
Test data is missing from hackage tarball

### ISSUE THREAD

**Issue by sternenseemann** [aleksey-makarov/melf#1]
It's not possible to run the tests from the hackage tarball, as the testdata is not included in `extra-source-files`.

**Comment by aleksey-makarov** [comment]
Is it required to be able to run the tests from the hackage tarball?  The test data is huge, I did not want to make the hackage tarball big.

**Comment by sternenseemann** [comment]
It is not technically a requirement. Stackage (which is opt-in and requires it) and us (that is nixpkgs) use them to verify that a package is working correctly before shipping it to downstream users. Using the hackage tarballs for this makes this less complicated.

You are free to not distribute the test data via hackage, we can just disable the tests (which is the current situation) or disable the test suites that require the data as well.

**Comment by aleksey-makarov** [comment]
As a trade off I think I will include two test files in the next version so that a reduced set of tests passes without any source intervention, but the tarball keeps small.  I would appreciate your judgement on this.   Thank you.

**Comment by sternenseemann** [comment]
Sounds like a good idea! If tests are a big concern, building from the github repo is always an option.
