### ISSUE TITLE
Not compatible with lens-5.3

### ISSUE THREAD

**Issue by ysangkok** [aleksey-makarov/melf#8]
See

* https://github.com/commercialhaskell/stackage/issues/7408

Note that you can get emails for these kinds of notifications, see [discourse](https://discourse.haskell.org/t/hackage-dep-bound-notifications-and-uploader-endorsements-for-new-users/8342). It's opt-in

**Comment by aleksey-makarov** [comment]
The commit [f74ca52afd4e25257d1d8f607619168a84c4024f](https://github.com/aleksey-makarov/melf/commit/f74ca52afd4e25257d1d8f607619168a84c4024f) fixes this.  All CI test passed.
I have not created a new release, instead created a revision on hackage.  Hope that's ok.
